### ISSUE TITLE
Odd Cassandra exceptions: 

### ISSUE THREAD

**Issue by acron0** [MastodonC/witan.app#29]
```
Cassandra version 2.2.2
[cc.qbits/alia "2.10.0"]
[cc.qbits/hayt "3.0.0-rc2"]
```

Starting the sever and doing a single curl produces this output:

```
Started nREPL server on port 7889
16:28:52.632 INFO  o.e.j.s.Server  - jetty-7.6.13.v20130916
16:28:52.656 INFO  o.e.j.s.AbstractConnector  - Started SelectChannelConnector@0.0.0.0:3000
Started server on port 3000
16:29:12.092 INFO  c.d.d.c.NettyUtil  - Detected shaded Netty classes in the classpath; native epoll transport will not work properly, defaulting to NIO.
16:29:12.344 ERROR c.d.d.c.TableMetadata  - Error parsing schema options for table system_traces.events: Cluster.getMetadata().getKeyspace("system_traces").getTable("events").getOptions() will return null
java.lang.IllegalArgumentException: Not a JSON map: KEYS_ONLY
	at com.datastax.driver.core.SimpleJSONParser.parseStringMap(SimpleJSONParser.java:77) ~[cassandra-driver-core-2.1.8-shaded.jar:na]
	at com.datastax.driver.core.TableMetadata$Options.<init>(TableMetadata.java:606) ~[cassandra-driver-core-2.1.8-shaded.jar:na]
	at com.datastax.driver.core.TableMetadata.build(TableMetadata.java:127) ~[cassandra-driver-core-2.1.8-shaded.jar:na]
	at com.datastax.driver.core.Metadata.buildTables(Metadata.java:183) [cassandra-driver-core-2.1.8-shaded.jar:na]
	at com.datastax.driver.core.Metadata.buildKeyspaces(Metadata.java:144) [cassandra-driver-core-2.1.8-shaded.jar:na]
	at com.datastax.driver.core.Metadata.rebuildSchema(Metadata.java:64) [cassandra-driver-core-2.1.8-shaded.jar:na]
	at com.datastax.driver.core.ControlConnection.refreshSchema(ControlConnection.java:370) [cassandra-driver-core-2.1.8-shaded.jar:na]
	at com.datastax.driver.core.ControlConnection.tryConnect(ControlConnection.java:267) [cassandra-driver-core-2.1.8-shaded.jar:na]
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:194) [cassandra-driver-core-2.1.8-shaded.jar:na]
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:86) [cassandra-driver-core-2.1.8-shaded.jar:na]
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1409) [cassandra-driver-core-2.1.8-shaded.jar:na]
	at com.datastax.driver.core.Cluster.init(Cluster.java:160) [cassandra-driver-core-2.1.8-shaded.jar:na]
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:338) [cassandra-driver-core-2.1.8-shaded.jar:na]
	at com.datastax.driver.core.Cluster.connect(Cluster.java:283) [cassandra-driver-core-2.1.8-shaded.jar:na]
	at qbits.alia$connect.invoke(alia.clj:194) [na:na]
	at witan.app.config$session.invoke(config.clj:23) [na:na]
	at witan.app.config$store_execute.invoke(config.clj:27) [na:na]
	at witan.app.config$exec.invoke(config.clj:32) [na:na]
	at witan.app.user$retrieve_user_by_username.invoke(user.clj:30) [na:na]
	at witan.app.user$user_valid_QMARK_.invoke(user.clj:43) [na:na]
	at witan.app.handler$login.invoke(handler.clj:56) [na:na]
	at witan.app.handler$fn__27456$fn__27457.invoke(handler.clj:109) [na:na]
	at compojure.core$make_route$fn__2887.invoke(core.clj:130) [na:na]
	at compojure.core$wrap_route_middleware$fn__2883.invoke(core.clj:118) [na:na]
	at compojure.core$if_route$fn__2855.invoke(core.clj:41) [na:na]
	at compojure.core$if_method$fn__2847.invoke(core.clj:27) [na:na]
	at compojure.api.meta$body_coercer_middleware$fn__25060.invoke(meta.clj:59) [na:na]
	at compojure.core$routing$fn__2894.invoke(core.clj:144) [na:na]
	at clojure.core$some.invoke(core.clj:2570) [clojure-1.7.0.jar:na]
	at compojure.core$routing.doInvoke(core.clj:144) [na:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:139) [clojure-1.7.0.jar:na]
	at clojure.core$apply.invoke(core.clj:632) [clojure-1.7.0.jar:na]
	at compojure.core$routes$fn__2898.invoke(core.clj:149) [na:na]
	at compojure.core$routing$fn__2894.invoke(core.clj:144) [na:na]
	at clojure.core$some.invoke(core.clj:2570) [clojure-1.7.0.jar:na]
	at compojure.core$routing.doInvoke(core.clj:144) [na:na]
	at clojure.lang.RestFn.invoke(RestFn.java:423) [clojure-1.7.0.jar:na]
	at witan.app.handler$fn__27456.invoke(handler.clj:104) [na:na]
	at compojure.core$if_context$fn__2956.invoke(core.clj:211) [na:na]
	at compojure.core$routing$fn__2894.invoke(core.clj:144) [na:na]
	at clojure.core$some.invoke(core.clj:2570) [clojure-1.7.0.jar:na]
	at compojure.core$routing.doInvoke(core.clj:144) [na:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:139) [clojure-1.7.0.jar:na]
	at clojure.core$apply.invoke(core.clj:632) [clojure-1.7.0.jar:na]
	at compojure.core$routes$fn__2898.invoke(core.clj:149) [na:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:154) [clojure-1.7.0.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:144) [clojure-1.7.0.jar:na]
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29) [clojure-1.7.0.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:408) [clojure-1.7.0.jar:na]
	at ring.middleware.http_response$wrap_http_response$fn__22401.invoke(http_response.clj:8) [na:na]
	at ring.swagger.middleware$wrap_swagger_data$fn__23163.invoke(middleware.clj:33) [na:na]
	at compojure.api.middleware$wrap_options$fn__23378.invoke(middleware.clj:93) [na:na]
	at ring.middleware.format_params$wrap_format_params$fn__22187.invoke(format_params.clj:111) [na:na]
	at ring.middleware.format_params$wrap_format_params$fn__22187.invoke(format_params.clj:113) [na:na]
	at ring.middleware.format_params$wrap_format_params$fn__22187.invoke(format_params.clj:113) [na:na]
	at ring.middleware.format_params$wrap_format_params$fn__22187.invoke(format_params.clj:113) [na:na]
	at ring.middleware.format_params$wrap_format_params$fn__22187.invoke(format_params.clj:113) [na:na]
	at compojure.api.middleware$wrap_exceptions$fn__23367.invoke(middleware.clj:59) [na:na]
	at ring.middleware.format_response$wrap_format_response$fn__22326.invoke(format_response.clj:175) [na:na]
	at ring.middleware.keyword_params$wrap_keyword_params$fn__9578.invoke(keyword_params.clj:35) [na:na]
	at ring.middleware.nested_params$wrap_nested_params$fn__9628.invoke(nested_params.clj:84) [na:na]
	at ring.middleware.params$wrap_params$fn__3121.invoke(params.clj:64) [na:na]
	at compojure.api.middleware$wrap_options$fn__23378.invoke(middleware.clj:93) [na:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:154) [clojure-1.7.0.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:144) [clojure-1.7.0.jar:na]
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29) [clojure-1.7.0.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:408) [clojure-1.7.0.jar:na]
	at buddy.auth.middleware$wrap_authorization$fn__8462.invoke(middleware.clj:81) [na:na]
	at buddy.auth.middleware$wrap_authentication$fn__8447.invoke(middleware.clj:46) [na:na]
	at ring.middleware.cors$wrap_cors$fn__8549.invoke(cors.clj:148) [na:na]
	at clojure.lang.Var.invoke(Var.java:379) [clojure-1.7.0.jar:na]
	at ring.middleware.reload$wrap_reload$fn__1158.invoke(reload.clj:18) [na:na]
	at ring.middleware.stacktrace$wrap_stacktrace_log$fn__911.invoke(stacktrace.clj:17) [na:na]
	at ring.middleware.stacktrace$wrap_stacktrace_web$fn__973.invoke(stacktrace.clj:80) [na:na]
	at ring.adapter.jetty$proxy_handler$fn__97.invoke(jetty.clj:20) [na:na]
	at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source) [na:na]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [jetty-server-7.6.13.v20130916.jar:7.6.13.v20130916]
	at org.eclipse.jetty.server.Server.handle(Server.java:369) [jetty-server-7.6.13.v20130916.jar:7.6.13.v20130916]
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:486) [jetty-server-7.6.13.v20130916.jar:7.6.13.v20130916]
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:944) [jetty-server-7.6.13.v20130916.jar:7.6.13.v20130916]
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1005) [jetty-server-7.6.13.v20130916.jar:7.6.13.v20130916]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865) [jetty-http-7.6.13.v20130916.jar:7.6.13.v20130916]
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240) [jetty-http-7.6.13.v20130916.jar:7.6.13.v20130916]
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) [jetty-server-7.6.13.v20130916.jar:7.6.13.v20130916]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668) [jetty-io-7.6.13.v20130916.jar:7.6.13.v20130916]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52) [jetty-io-7.6.13.v20130916.jar:7.6.13.v20130916]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) [jetty-util-7.6.13.v20130916.jar:7.6.13.v20130916]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) [jetty-util-7.6.13.v20130916.jar:7.6.13.v20130916]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
16:29:12.346 ERROR c.d.d.c.TableMetadata  - Error parsing schema options for table system_traces.sessions: Cluster.getMetadata().getKeyspace("system_traces").getTable("sessions").getOptions() will return null
java.lang.IllegalArgumentException: Not a JSON map: KEYS_ONLY
	at com.datastax.driver.core.SimpleJSONParser.parseStringMap(SimpleJSONParser.java:77) ~[cassandra-driver-core-2.1.8-shaded.jar:na]
	at com.datastax.driver.core.TableMetadata$Options.<init>(TableMetadata.java:606) ~[cassandra-driver-core-2.1.8-shaded.jar:na]
	at com.datastax.driver.core.TableMetadata.build(TableMetadata.java:127) ~[cassandra-driver-core-2.1.8-shaded.jar:na]
	at com.datastax.driver.core.Metadata.buildTables(Metadata.java:183) [cassandra-driver-core-2.1.8-shaded.jar:na]
	at com.datastax.driver.core.Metadata.buildKeyspaces(Metadata.java:144) [cassandra-driver-core-2.1.8-shaded.jar:na]
	at com.datastax.driver.core.Metadata.rebuildSchema(Metadata.java:64) [cassandra-driver-core-2.1.8-shaded.jar:na]
	at com.datastax.driver.core.ControlConnection.refreshSchema(ControlConnection.java:370) [cassandra-driver-core-2.1.8-shaded.jar:na]
	at com.datastax.driver.core.ControlConnection.tryConnect(ControlConnection.java:267) [cassandra-driver-core-2.1.8-shaded.jar:na]
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:194) [cassandra-driver-core-2.1.8-shaded.jar:na]
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:86) [cassandra-driver-core-2.1.8-shaded.jar:na]
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1409) [cassandra-driver-core-2.1.8-shaded.jar:na]
	at com.datastax.driver.core.Cluster.init(Cluster.java:160) [cassandra-driver-core-2.1.8-shaded.jar:na]
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:338) [cassandra-driver-core-2.1.8-shaded.jar:na]
	at com.datastax.driver.core.Cluster.connect(Cluster.java:283) [cassandra-driver-core-2.1.8-shaded.jar:na]
	at qbits.alia$connect.invoke(alia.clj:194) [na:na]
	at witan.app.config$session.invoke(config.clj:23) [na:na]
	at witan.app.config$store_execute.invoke(config.clj:27) [na:na]
	at witan.app.config$exec.invoke(config.clj:32) [na:na]
	at witan.app.user$retrieve_user_by_username.invoke(user.clj:30) [na:na]
	at witan.app.user$user_valid_QMARK_.invoke(user.clj:43) [na:na]
	at witan.app.handler$login.invoke(handler.clj:56) [na:na]
	at witan.app.handler$fn__27456$fn__27457.invoke(handler.clj:109) [na:na]
	at compojure.core$make_route$fn__2887.invoke(core.clj:130) [na:na]
	at compojure.core$wrap_route_middleware$fn__2883.invoke(core.clj:118) [na:na]
	at compojure.core$if_route$fn__2855.invoke(core.clj:41) [na:na]
	at compojure.core$if_method$fn__2847.invoke(core.clj:27) [na:na]
	at compojure.api.meta$body_coercer_middleware$fn__25060.invoke(meta.clj:59) [na:na]
	at compojure.core$routing$fn__2894.invoke(core.clj:144) [na:na]
	at clojure.core$some.invoke(core.clj:2570) [clojure-1.7.0.jar:na]
	at compojure.core$routing.doInvoke(core.clj:144) [na:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:139) [clojure-1.7.0.jar:na]
	at clojure.core$apply.invoke(core.clj:632) [clojure-1.7.0.jar:na]
	at compojure.core$routes$fn__2898.invoke(core.clj:149) [na:na]
	at compojure.core$routing$fn__2894.invoke(core.clj:144) [na:na]
	at clojure.core$some.invoke(core.clj:2570) [clojure-1.7.0.jar:na]
	at compojure.core$routing.doInvoke(core.clj:144) [na:na]
	at clojure.lang.RestFn.invoke(RestFn.java:423) [clojure-1.7.0.jar:na]
	at witan.app.handler$fn__27456.invoke(handler.clj:104) [na:na]
	at compojure.core$if_context$fn__2956.invoke(core.clj:211) [na:na]
	at compojure.core$routing$fn__2894.invoke(core.clj:144) [na:na]
	at clojure.core$some.invoke(core.clj:2570) [clojure-1.7.0.jar:na]
	at compojure.core$routing.doInvoke(core.clj:144) [na:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:139) [clojure-1.7.0.jar:na]
	at clojure.core$apply.invoke(core.clj:632) [clojure-1.7.0.jar:na]
	at compojure.core$routes$fn__2898.invoke(core.clj:149) [na:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:154) [clojure-1.7.0.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:144) [clojure-1.7.0.jar:na]
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29) [clojure-1.7.0.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:408) [clojure-1.7.0.jar:na]
	at ring.middleware.http_response$wrap_http_response$fn__22401.invoke(http_response.clj:8) [na:na]
	at ring.swagger.middleware$wrap_swagger_data$fn__23163.invoke(middleware.clj:33) [na:na]
	at compojure.api.middleware$wrap_options$fn__23378.invoke(middleware.clj:93) [na:na]
	at ring.middleware.format_params$wrap_format_params$fn__22187.invoke(format_params.clj:111) [na:na]
	at ring.middleware.format_params$wrap_format_params$fn__22187.invoke(format_params.clj:113) [na:na]
	at ring.middleware.format_params$wrap_format_params$fn__22187.invoke(format_params.clj:113) [na:na]
	at ring.middleware.format_params$wrap_format_params$fn__22187.invoke(format_params.clj:113) [na:na]
	at ring.middleware.format_params$wrap_format_params$fn__22187.invoke(format_params.clj:113) [na:na]
	at compojure.api.middleware$wrap_exceptions$fn__23367.invoke(middleware.clj:59) [na:na]
	at ring.middleware.format_response$wrap_format_response$fn__22326.invoke(format_response.clj:175) [na:na]
	at ring.middleware.keyword_params$wrap_keyword_params$fn__9578.invoke(keyword_params.clj:35) [na:na]
	at ring.middleware.nested_params$wrap_nested_params$fn__9628.invoke(nested_params.clj:84) [na:na]
	at ring.middleware.params$wrap_params$fn__3121.invoke(params.clj:64) [na:na]
	at compojure.api.middleware$wrap_options$fn__23378.invoke(middleware.clj:93) [na:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:154) [clojure-1.7.0.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:144) [clojure-1.7.0.jar:na]
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29) [clojure-1.7.0.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:408) [clojure-1.7.0.jar:na]
	at buddy.auth.middleware$wrap_authorization$fn__8462.invoke(middleware.clj:81) [na:na]
	at buddy.auth.middleware$wrap_authentication$fn__8447.invoke(middleware.clj:46) [na:na]
	at ring.middleware.cors$wrap_cors$fn__8549.invoke(cors.clj:148) [na:na]
	at clojure.lang.Var.invoke(Var.java:379) [clojure-1.7.0.jar:na]
	at ring.middleware.reload$wrap_reload$fn__1158.invoke(reload.clj:18) [na:na]
	at ring.middleware.stacktrace$wrap_stacktrace_log$fn__911.invoke(stacktrace.clj:17) [na:na]
	at ring.middleware.stacktrace$wrap_stacktrace_web$fn__973.invoke(stacktrace.clj:80) [na:na]
	at ring.adapter.jetty$proxy_handler$fn__97.invoke(jetty.clj:20) [na:na]
	at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source) [na:na]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [jetty-server-7.6.13.v20130916.jar:7.6.13.v20130916]
	at org.eclipse.jetty.server.Server.handle(Server.java:369) [jetty-server-7.6.13.v20130916.jar:7.6.13.v20130916]
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:486) [jetty-server-7.6.13.v20130916.jar:7.6.13.v20130916]
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:944) [jetty-server-7.6.13.v20130916.jar:7.6.13.v20130916]
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1005) [jetty-server-7.6.13.v20130916.jar:7.6.13.v20130916]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865) [jetty-http-7.6.13.v20130916.jar:7.6.13.v20130916]
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240) [jetty-http-7.6.13.v20130916.jar:7.6.13.v20130916]
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) [jetty-server-7.6.13.v20130916.jar:7.6.13.v20130916]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668) [jetty-io-7.6.13.v20130916.jar:7.6.13.v20130916]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52) [jetty-io-7.6.13.v20130916.jar:7.6.13.v20130916]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) [jetty-util-7.6.13.v20130916.jar:7.6.13.v20130916]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) [jetty-util-7.6.13.v20130916.jar:7.6.13.v20130916]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
16:29:12.373 INFO  c.d.d.c.p.DCAwareRoundRobinPolicy  - Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
16:29:12.373 INFO  c.d.d.c.Cluster  - New Cassandra host localhost/127.0.0.1:9042 added
```

curl
```
curl 'http://localhost:3000/api/login' -H 'Origin: http://localhost:3449' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-GB,en-US;q=0.8,en;q=0.6' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36' -H 'Content-Type: application/json; charset=UTF-8' -H 'Accept: application/json, application/edn, application/transit+json, text/plain, text/html, */*' -H 'Referer: http://localhost:3449/' -H 'Connection: keep-alive' --data-binary '{"username":"support@mastodonc.com","password":"secret"}' --compressed
```

**Comment by acron0** [comment]
Since moving C* into a docker container this has gone away
